### ISSUE TITLE
update cluster exercise from anaconda2 to anaconda3?

### ISSUE THREAD

**Issue by mekman** [Donders-Institute/hpc-wiki-v2#10]
https://github.com/Donders-Institute/hpc-wiki-v2/blob/master/docs/cluster_howto/exercise_python/exercise.rst

shows the usage of anaconda2 which defaults to python 2.7.13

@hurngchunlee Would you be open to changing this to anaconda3, which comes with python3? I recently started helping a student who used this exercise to get started with python, but then encountered many problems because python 2.7.

(I should say that I am still using python 2.7 for some old projects myself, but if I were to start today, I would do it in python3)

WDYT?

**Comment by marcelzwiers** [comment]
I think it's a good idea so I changed (and fixed) the page:

https://github.com/Donders-Institute/hpc-wiki-v2/commit/a983a69f7da6644571f4d795974d84cf22bdc9f5

Op do 19 okt 2023 om 13:17 schreef Matthias Ekman ***@***.***

**Comment by marcelzwiers** [comment]
Ok, the RTD build is failing:

Error

The configuration key "build.os" is required to build your documentation.
Read more at
https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
https://readthedocs.org/projects/dccn-hpc-wiki/builds/22279982/


Op do 19 okt 2023 om 13:39 schreef Marcel Zwiers ***@***.***>:

**Comment by marcelzwiers** [comment]
Fixed it :-)

Op do 19 okt 2023 om 13:43 schreef Marcel Zwiers ***@***.***>:

**Comment by mekman** [comment]
@marcelzwiers thanks. Just to double check, is ```python nibabel_example.py``` running fine with python 3?

**Comment by marcelzwiers** [comment]
I didn't test-run it but it the python script is just:
```python
#!/usr/bin/env python

import nibabel as nib

img = nib.load("example4d.nii.gz")

print( img.shape )
```
I don't see how this depends on the python version
